name: Deploy Docker Compose to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app

      - name: Deploy Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << EOF
            sudo su -c 'cd /home/ec2-user/app && export CHATGPT_API_KEY=${{ secrets.CHATGPT_API_KEY }} && export BASE_URL=${{ secrets.EC2_HOST }} && docker-compose down && docker-compose up --build -d'
          EOF